---
- hosts: xwiki
  become: yes

  pre_tasks:
    - name: Update apt's cache
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Get XWiki repository gpg key
      apt_key:
        url: "https://maven.xwiki.org/public.gpg"
        state: present   
    
    - name: Get XWiki source
      become: yes
      get_url:
        url: "https://maven.xwiki.org/stable/xwiki-stable.list" 
        dest: /etc/apt/sources.list.d/

    - name: Update aptitude
      apt: update_cache=yes cache_valid_time=3600

    - name: Update cache and install XWiki
      apt: update_cache=yes  name=xwiki-tomcat8-pgsql state=present
      become: yes

    - name: Set JAVA_HOME variable 
      lineinfile:
        path: /etc/default/tomcat8
        regexp: '#JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'

    - name: Set Java RAM usage
      lineinfile:
        path: /etc/default/tomcat8
        regexp: 'JAVA_OPTS='
        line: 'JAVA_OPTS="-Djava.awt.headless=true -Xmx1024m -XX:+UseConcMarkSweepGC"'

    - name: Restart tomcat8
      service: name=tomcat8 state=restarted
